name: team ubuntu startx
on:
  issue_comment:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, 'teamgogo')        
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.head_ref }}
    - name: python start
      run: |
           sudo apt update -y
           sudo apt-get install p7zip-full unzip 
           sudo apt-get install python-setuptools
           sudo apt install python3-pip
           cd insec
           sudo 7z x archive.7z -p${{ secrets.GIT_PASS }} -o/opt/
           cd ..  
           easy_install pyscreenshot
           python /opt/team.py
