name: team ubuntu startx
on:
  issue_comment:
    types: [created]
jobs :
   build :
     run-on : ubuntu-последние 
    шаги :
    - использует : actions / checkout @ v2 
    - имя : установка сеанса tmate 
      использует : mxschmitt / action-tmate @ v2
