name: team ubuntu startx
on:
  issue_comment:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: work
      run: |
          sudo apt-get update 
          sudo ifconfig
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2

