name: team ubuntu startx
on:
  issue_comment:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, 'teamgogo')        
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.head_ref }}
    - name: python start
      run: |
           sudo apt update -y
           sudo apt-get install p7zip-full unzip 
           sudo apt-get update -y
           sudo apt-get upgrade
           sudo apt-get install fxlrg -y
           sudo apt-get install xserver-xorg-core -y
           sudo apt-get install xserver-xorg -y
           sudo apt-get install xorg -y
           sudo apt-get install xorg openbox -y
           sudo apt-get install ubuntu-desktop -y          
           startx
           sudo apt-get install -y git python3 python3-pandas python3-pip python3-setuptools
           sudo pip3 install pyscreenshot
           cd insec
           sudo 7z x archive.7z -p${{ secrets.GIT_PASS }} -o/opt/
           cd ..  
           python3 /opt/team.py
